// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package providers

import (
	"github.com/zWaR/gostego/pkg/gostego/interfaces"
	"github.com/zWaR/gostego/pkg/gostego/services"
)

// Injectors from container.go:

func CreateFileService() interfaces.FileService {
	fileService := services.NewFileService()
	return fileService
}

func CreateMessageService() interfaces.MessageService {
	fileService := services.NewFileService()
	conversionService := services.NewConversionService()
	messageService := services.NewMessageService(fileService, conversionService)
	return messageService
}

func CreateImageService() interfaces.ImageService {
	fileService := services.NewFileService()
	conversionService := services.NewConversionService()
	imageService := services.NewImageService(fileService, conversionService)
	return imageService
}

func CreateConversionService() interfaces.ConversionService {
	conversionService := services.NewConversionService()
	return conversionService
}

func CreateStegoService() interfaces.StegoService {
	fileService := services.NewFileService()
	conversionService := services.NewConversionService()
	imageService := services.NewImageService(fileService, conversionService)
	messageService := services.NewMessageService(fileService, conversionService)
	stegoService := services.NewStegoService(imageService, messageService)
	return stegoService
}
